apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
spec:
  selector:
    matchLabels:
      app: helloworld-app
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
        - name: helloworld-app
          image: karthequian/helloworld:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/helloworld"
            backend:
              service:
                name: helloworld-service
                port:
                  number: 80
---
